# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-07-14 16:46+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: nikkurie <@nikkurie>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: ja-JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: selfdrive/controls/lib/events.py:146
msgid "openpilot Unavailable"
msgstr "オープンパイロットは利用できません"

#: selfdrive/controls/lib/events.py:153 selfdrive/controls/lib/events.py:160
msgid "TAKE CONTROL IMMEDIATELY"
msgstr "すぐにハンドルを持って"

#: selfdrive/controls/lib/events.py:180 selfdrive/controls/lib/events.py:330
#: selfdrive/controls/lib/events.py:356 selfdrive/controls/lib/events.py:420
#: selfdrive/controls/lib/events.py:472 selfdrive/controls/lib/events.py:524
#: selfdrive/controls/lib/events.py:534 selfdrive/controls/lib/events.py:543
msgid "TAKE CONTROL"
msgstr "ハンドルを持って"

#: selfdrive/controls/lib/events.py:181
msgid "Steer Unavailable Below"
msgstr "横の制御が無効になり速度が以下になります"

#: selfdrive/controls/lib/events.py:190
msgid "Drive Above"
msgstr "制限速度以上の運転をしてください"

#: selfdrive/controls/lib/events.py:189
msgid "Calibration in Progress:"
msgstr "キャリブレーション中:"

#: selfdrive/controls/lib/events.py:197
msgid "Poor GPS reception"
msgstr "GPS受信不良"

#: selfdrive/controls/lib/events.py:198
msgid "If sky is visible, contact support"
msgstr "地下・トンネルでない場合は、カスタマーサービスに連絡ください"

#: selfdrive/controls/lib/events.py:198
msgid "Check GPS antenna placement"
msgstr "GPSアンテナの位置を確認してください。"

#: selfdrive/controls/lib/events.py:203
msgid "Cruise Mode Disabled"
msgstr "クルーズモードをオフ"

#: selfdrive/controls/lib/events.py:205
msgid "Main Switch Off"
msgstr "メインスイッチをオフ"

#: selfdrive/controls/lib/events.py:215
msgid "DEBUG ALERT"
msgstr "テストメッセージを削除"

#: selfdrive/controls/lib/events.py:223
msgid "Be ready to take over at any time"
msgstr "いつでも引き継げるよう準備しておいてください。"

#: selfdrive/controls/lib/events.py:224 selfdrive/controls/lib/events.py:240
#: selfdrive/controls/lib/events.py:248 selfdrive/controls/lib/events.py:256
msgid "Always keep hands on wheel and eyes on road"
msgstr "常にハンドルに触れ、道路から目を離さない"

#: selfdrive/controls/lib/events.py:231
msgid "WARNING: White panda is deprecated"
msgstr "警告: ホワイトパンダは推奨されていません。"

#: selfdrive/controls/lib/events.py:232 selfdrive/controls/lib/events.py:272
msgid "Upgrade to comma two or black panda"
msgstr "コンマ2やブラックパンダにアップグレード"

#: selfdrive/controls/lib/events.py:239
msgid "WARNING: This branch is not tested"
msgstr "警告: このブランチはテストされていません"

#: selfdrive/controls/lib/events.py:247
msgid "Dashcam mode"
msgstr "ダッシュカムモード"

#: selfdrive/controls/lib/events.py:255
msgid "Dashcam mode for unsupported car"
msgstr "未対応車のためダッシュカムモードのみ"

#: selfdrive/controls/lib/events.py:263
msgid "Unsupported Giraffe Configuration"
msgstr "サポートされていないGiraffeの設定"

#: selfdrive/controls/lib/events.py:264
msgid "Visit comma.ai/tg"
msgstr "comma.ai/tg を参照"

#: selfdrive/controls/lib/events.py:271
msgid "White Panda Is No Longer Supported"
msgstr "ホワイトパンダはサポート終了しました"

#: selfdrive/controls/lib/events.py:275
msgid "White panda is no longer supported"
msgstr "ホワイトパンダはサポート終了しました"

#: selfdrive/controls/lib/events.py:280
msgid "Stock LKAS is turned on"
msgstr "純正LKASがオン"

#: selfdrive/controls/lib/events.py:281
msgid "Turn off stock LKAS to engage"
msgstr "純正LKASをオフにしてエンゲージ"

#: selfdrive/controls/lib/events.py:290
msgid "Community Feature Detected"
msgstr "コミュニティ開発の機能を検出"

#: selfdrive/controls/lib/events.py:291
msgid "Enable Community Features in Developer Settings"
msgstr "開発者設定でコミュニティ機能を有効にする"

#: selfdrive/controls/lib/events.py:298
msgid "Dashcam Mode"
msgstr "ダッシュカムモード"

#: selfdrive/controls/lib/events.py:299
msgid "Car Unrecognized"
msgstr "認識できない車"

#: selfdrive/controls/lib/events.py:306 selfdrive/controls/lib/events.py:314
#: selfdrive/controls/lib/events.py:322
msgid "BRAKE!"
msgstr "ブレーキ！"

#: selfdrive/controls/lib/events.py:307
msgid "Stock AEB: Risk of Collision"
msgstr "衝突の危険"

#: selfdrive/controls/lib/events.py:315
msgid "Stock FCW: Risk of Collision"
msgstr "衝突の危険"

#: selfdrive/controls/lib/events.py:323
msgid "Risk of Collision"
msgstr "衝突の危険"

#: selfdrive/controls/lib/events.py:331
msgid "Lane Departure Detected"
msgstr "車線逸脱を検知"

#: selfdrive/controls/lib/events.py:340
msgid "openpilot will not brake while gas pressed"
msgstr "アクセル中、オープンパイロットはブレーキをかけません"

#: selfdrive/controls/lib/events.py:348
msgid "Vehicle Parameter Identification Failed"
msgstr "車両パラメータの識別に失敗しました。"

#: selfdrive/controls/lib/events.py:357 selfdrive/controls/lib/events.py:525
#: selfdrive/controls/lib/events.py:528
msgid "Steering Temporarily Unavailable"
msgstr "ステアリングは一時的に利用不可"

#: selfdrive/controls/lib/events.py:364
msgid "KEEP EYES ON ROAD: Driver Distracted"
msgstr "道路から目を離さないで:注意散漫です"

#: selfdrive/controls/lib/events.py:372
msgid "KEEP EYES ON ROAD"
msgstr "道路から目を離さないで"

#: selfdrive/controls/lib/events.py:373
msgid "Driver Appears Distracted"
msgstr "ドライバーは注意散漫に見えます"

#: selfdrive/controls/lib/events.py:380 selfdrive/controls/lib/events.py:404
msgid "DISENGAGE IMMEDIATELY"
msgstr "すぐに解除してください"

#: selfdrive/controls/lib/events.py:381
msgid "Driver Was Distracted"
msgstr "ドライバーは注意力散漫"

#: selfdrive/controls/lib/events.py:388
msgid "TOUCH STEERING WHEEL: No Face Detected"
msgstr "ハンドルに触れて:顔が検出できない"

#: selfdrive/controls/lib/events.py:396
msgid "TOUCH STEERING WHEEL"
msgstr "ハンドルに触れて"

#: selfdrive/controls/lib/events.py:397
msgid "Driver Is Unresponsive"
msgstr "ドライバーが無反応"

#: selfdrive/controls/lib/events.py:405
msgid "Driver Was Unresponsive"
msgstr "ドライバーが無反応でした"

#: selfdrive/controls/lib/events.py:412
msgid "CHECK DRIVER FACE VISIBILITY"
msgstr "ドライバーの顔の視認性を確認"

#: selfdrive/controls/lib/events.py:413
msgid "Driver Monitor Model Output Uncertain"
msgstr "ドライバー監視モデルが不完全"

#: selfdrive/controls/lib/events.py:421
msgid "Resume Driving Manually"
msgstr "手動で運転を再開"

#: selfdrive/controls/lib/events.py:428
msgid "STOPPED"
msgstr "停止"

#: selfdrive/controls/lib/events.py:429
msgid "Press Resume to Move"
msgstr "Resumeを押して移動します。"

#: selfdrive/controls/lib/events.py:440
msgid "Steer Left to Start Lane Change"
msgstr "左ハンドルで車線変更を開始"

#: selfdrive/controls/lib/events.py:441 selfdrive/controls/lib/events.py:449
#: selfdrive/controls/lib/events.py:457 selfdrive/controls/lib/events.py:465
#: selfdrive/controls/lib/events.py:793 selfdrive/controls/lib/events.py:801
#: selfdrive/controls/lib/events.py:809
msgid "Monitor Other Vehicles"
msgstr "他の車両を監視"

#: selfdrive/controls/lib/events.py:448
msgid "Steer Right to Start Lane Change"
msgstr "右ハンドルで車線変更を開始"

#: selfdrive/controls/lib/events.py:456
msgid "Car Detected in Blindspot"
msgstr "ブラインドスポットで車両を発見"

#: selfdrive/controls/lib/events.py:464 selfdrive/controls/lib/events.py:808
msgid "Changing Lane"
msgstr "レーンチェンジ中"

#: selfdrive/controls/lib/events.py:473
msgid "Turn Exceeds Steering Limit"
msgstr "ステアリングリミットを超えています"

#: selfdrive/controls/lib/events.py:498
msgid "Brake Hold Active"
msgstr "サイドブレーキが作動"

#: selfdrive/controls/lib/events.py:503
msgid "Park Brake Engaged"
msgstr "サイドブレーキ作動中"

#: selfdrive/controls/lib/events.py:508
msgid "Pedal Pressed During Attempt"
msgstr "ペダル/ブレーキを検出"

#: selfdrive/controls/lib/events.py:519
msgid "Enable Adaptive Cruise"
msgstr "ACCを有効化"

#: selfdrive/controls/lib/events.py:535 selfdrive/controls/lib/events.py:538
msgid "Vision Model Output Uncertain"
msgstr "映像が不明瞭です"

#: selfdrive/controls/lib/events.py:544
msgid "Attempting Refocus: Camera Focus Invalid"
msgstr "再フォーカス中です"

#: selfdrive/controls/lib/events.py:550
msgid "Out of Storage Space"
msgstr "空き容量不足"

#: selfdrive/controls/lib/events.py:555
msgid "Speed Too Low"
msgstr "速度が遅すぎます"

#: selfdrive/controls/lib/events.py:560 selfdrive/controls/lib/events.py:564
msgid "NEOS Update Required"
msgstr "NEOSの更新が必要"

#: selfdrive/controls/lib/events.py:561
msgid "Please Wait for Update"
msgstr "更新をお待ちください"

#: selfdrive/controls/lib/events.py:569 selfdrive/controls/lib/events.py:573
msgid "No Data from Device Sensors"
msgstr "デバイスセンサからのデータがありません"

#: selfdrive/controls/lib/events.py:570 selfdrive/controls/lib/events.py:583
#: selfdrive/controls/lib/events.py:665
msgid "Reboot your Device"
msgstr "デバイスを再起動"

#: selfdrive/controls/lib/events.py:582 selfdrive/controls/lib/events.py:586
msgid "Speaker not found"
msgstr "スピーカーが見つかりません"

#: selfdrive/controls/lib/events.py:590
msgid "Distraction Level Too High"
msgstr "注意力散漫すぎます"

#: selfdrive/controls/lib/events.py:594
msgid "System Overheated"
msgstr "オーバーヒート"

#: selfdrive/controls/lib/events.py:595
msgid "System overheated"
msgstr "オーバーヒート"

#: selfdrive/controls/lib/events.py:599 selfdrive/controls/lib/events.py:600
msgid "Gear not D"
msgstr "Dではない"

#: selfdrive/controls/lib/events.py:604
msgid "Calibration Invalid: Reposition Device and Recalibrate"
msgstr "キャリブレーションが無効です。再実行してください。"

#: selfdrive/controls/lib/events.py:605
msgid "Calibration Invalid: Reposition Device & Recalibrate"
msgstr "キャリブレーションが無効です。再実行してください。"

#: selfdrive/controls/lib/events.py:609 selfdrive/controls/lib/events.py:611
msgid "Calibration in Progress"
msgstr "キャリブレーション"

#: selfdrive/controls/lib/events.py:615
msgid "Door Open"
msgstr "ドアが開いています"

#: selfdrive/controls/lib/events.py:616
msgid "Door open"
msgstr "ドアが開いています"

#: selfdrive/controls/lib/events.py:620
msgid "Seatbelt Unlatched"
msgstr "シートベルト未着用"

#: selfdrive/controls/lib/events.py:621
msgid "Seatbelt unlatched"
msgstr "シートベルト未着用"

#: selfdrive/controls/lib/events.py:625 selfdrive/controls/lib/events.py:626
msgid "ESP Off"
msgstr "ESPオフ"

#: selfdrive/controls/lib/events.py:630 selfdrive/controls/lib/events.py:631
msgid "Low Battery"
msgstr "低バッテリー"

#: selfdrive/controls/lib/events.py:635 selfdrive/controls/lib/events.py:636
msgid "Communication Issue between Processes"
msgstr "プロセス間の通信の問題"

#: selfdrive/controls/lib/events.py:641 selfdrive/controls/lib/events.py:642
msgid "Radar Communication Issue"
msgstr "レーダー通信問題"

#: selfdrive/controls/lib/events.py:647 selfdrive/controls/lib/events.py:648
#: selfdrive/controls/lib/events.py:652 selfdrive/controls/lib/events.py:653
msgid "Radar Error: Restart the Car"
msgstr "レーダーエラー:車を再起動"

#: selfdrive/controls/lib/events.py:657 selfdrive/controls/lib/events.py:658
msgid "Driving model lagging"
msgstr "制御モデルに遅延がある"

#: selfdrive/controls/lib/events.py:662 selfdrive/controls/lib/events.py:668
msgid "Low Memory: Reboot Your Device"
msgstr "ローメモリ:デバイスを再起動"

#: selfdrive/controls/lib/events.py:664
msgid "RAM Critically Low"
msgstr "RAMが致命的に低い"

#: selfdrive/controls/lib/events.py:673 selfdrive/controls/lib/events.py:674
msgid "Controls Failed"
msgstr "制御失敗"

#: selfdrive/controls/lib/events.py:678
msgid "Controls Mismatch"
msgstr "制御不一致"

#: selfdrive/controls/lib/events.py:682 selfdrive/controls/lib/events.py:684
#: selfdrive/controls/lib/events.py:688
msgid "CAN Error: Check Connections"
msgstr "CANエラー:接続を確認"

#: selfdrive/controls/lib/events.py:692 selfdrive/controls/lib/events.py:698
msgid "LKAS Fault: Restart the Car"
msgstr "LKASの故障:車を再起動"

#: selfdrive/controls/lib/events.py:694
msgid "LKAS Fault: Restart the car to engage"
msgstr "LKASの故障:車を再起動後発進"

#: selfdrive/controls/lib/events.py:702 selfdrive/controls/lib/events.py:708
#: selfdrive/controls/lib/events.py:786
msgid "Cruise Fault: Restart the Car"
msgstr "クルーズ失敗:車を再起動"

#: selfdrive/controls/lib/events.py:704 selfdrive/controls/lib/events.py:782
msgid "Cruise Fault: Restart the car to engage"
msgstr "クルーズ失敗:車を再起動後発進"

#: selfdrive/controls/lib/events.py:712
msgid "Gas Fault: Restart the Car"
msgstr "アクセル故障:車を再起動"

#: selfdrive/controls/lib/events.py:713
msgid "Gas Error: Restart the Car"
msgstr "アクセルエラー:車を再起動"

#: selfdrive/controls/lib/events.py:717 selfdrive/controls/lib/events.py:718
msgid "Reverse Gear"
msgstr "Rに切り替え"

#: selfdrive/controls/lib/events.py:722
msgid "Cruise Is Off"
msgstr "クルーズコントロールオフ"

#: selfdrive/controls/lib/events.py:726 selfdrive/controls/lib/events.py:727
msgid "Planner Solution Error"
msgstr "Planner Solution エラー"

#: selfdrive/controls/lib/events.py:731 selfdrive/controls/lib/events.py:733
#: selfdrive/controls/lib/events.py:737
msgid "Harness Malfunction"
msgstr "ハーネスが故障"

#: selfdrive/controls/lib/events.py:734
msgid "Please Check Hardware"
msgstr "ハードウェアを確認して"

#: selfdrive/controls/lib/events.py:742 selfdrive/controls/lib/events.py:751
msgid "openpilot Canceled"
msgstr "オープンパイロットはキャンセルされました"

#: selfdrive/controls/lib/events.py:743
msgid "No close lead car"
msgstr "リードカー不在"

#: selfdrive/controls/lib/events.py:746
msgid "No Close Lead Car"
msgstr "リードカー不在"

#: selfdrive/controls/lib/events.py:752
msgid "Speed too low"
msgstr "速度が遅すぎる"

#: selfdrive/controls/lib/events.py:759 selfdrive/controls/lib/events.py:764
msgid "Speed Too High"
msgstr "速度が速すぎる"

#: selfdrive/controls/lib/events.py:760
msgid "Slow down to resume operation"
msgstr "速度を下げてオープンパイロットを再開"

#: selfdrive/controls/lib/events.py:765
msgid "Slow down to engage"
msgstr "速度を落として発進"

#: selfdrive/controls/lib/events.py:772
msgid "Please connect to Internet"
msgstr "インターネット接続を確認"

#: selfdrive/controls/lib/events.py:773
msgid "An Update Check Is Required to Engage"
msgstr "発進するには更新が必要です"

#: selfdrive/controls/lib/events.py:776
msgid "Please Connect to Internet"
msgstr "インターネット接続を確認"

#: selfdrive/controls/lib/events.py:792
msgid "Left ALC will start in 3s"
msgstr "左車線に移動します"

#: selfdrive/controls/lib/events.py:800
msgid "Right ALC will start in 3s"
msgstr "右車線に移動します"

#: selfdrive/controls/lib/events.py:816
msgid "STEERING REQUIRED: Lane Keeping OFF"
msgstr "操作が必要:レーンキープオフ"

#: selfdrive/controls/lib/events.py:824
msgid "STEERING REQUIRED: Blinkers ON"
msgstr "操作が必要:ウインカーオン"

#: selfdrive/controls/lib/events.py:832 selfdrive/controls/lib/events.py:837
msgid "Lead Car Is Moving"
msgstr "リードカーが移動しました"
